; CISCO Custom
[from-internal-custom]

; x-cisco-serviceuri
exten => _[x]-cisco-serviceuri-.,1,Goto(${EXTEN:19},1)

; pickup
exten => pickup,1,Pickup()
same => next,Hangup(normal_circuit_congestion)

; blfpickup
exten => _blfpickup-.,1,PickupChan(SIP/${EXTEN:10})
same => next,Hangup(normal_circuit_congestion)

; record
exten => record,1,Answer()
same => next,Wait(0.5)
same => next,Set(CONFBRIDGE(bridge,record_conference)=yes)
same => next,Set(CONFBRIDGE(bridge,record_file)=${RECORD_PEERNAME})
same => next,Set(CONFBRIDGE(user,quiet)=yes)
same => next,ConfBridge(${RECORD_UNIQUEID})
same => next,Hangup(normal_clearing)

; Enable call-forwarding
exten => _cfwdall-.,1,Answer
same => next,Set(SIPPEER(${CHANNEL(peername)},callforward)=${EXTEN:8})
same => next,Hangup(normal_clearing)

; Disable call-forwarding
exten => cfwdall,1,Answer
same => next,Set(SIPPEER(${CHANNEL(peername)},callforward)=)
same => next,Hangup(normal_clearing)

; idivert
exten => idivert,1,Answer()
same => next,Wait(0.5)
same => next,Set(MAILBOX=${SIPPEER(${IDIVERT_PEERNAME},mailbox)})
same => next,VoiceMail(${MAILBOX},b)
same => next,Hangup(normal_clearing)

; park
; If the parked call isn't retrieved in 60 seconds it will be sent to extension 370
;exten => park,1,Park(default,st(60)T(50)c(extensions,370,1))

; Remember to include the parked calls context
include => parked-calls

; dpark
exten => _dpark-.,1,Set(PARKINGEXTEN=${EXTEN:6})
same => next,Goto(park,1)