[default]
; If you never dial the parkext from the keypad you can just use 'park'
parkext=park
; 100 parking extension slots
parkpos=500-600
findslot=first
context=parked-calls
comebackcontext=parked-calls-timeout
parkinghints=yes
parkingtime=60
; Used by the Park Monitor feature on the 7800 series, 8800 series, 8961 and 9900 series models
remindertime=50
comebackdialtime=15
comebacktoorigin=yes