[cisco](!)
cisco_usecallmanager=yes
cisco_pickupnotify_alert=from,to
cisco_pickupnotify_timer=5
dndbusy=no
rpid_update=yes
rpid_immediate=yes
allowsubscribe=yes
notifyhold=yes
huntgroup_default=yes
cisco_keep_conference=yes
cisco_multiadmin_conference=yes
[{==Extension==}](+,cisco)
subscribe={==Extension==}
;[1005](+,cisco)
;subscribe=1200